### ISSUE TITLE
cron - timing - interval

### ISSUE THREAD

**Issue by m-osmani** [rsnapshot/rsnapshot#142]
Hey guys,

i realised that if you have for example this interval scheme:

retain                  daily   7
retain                  weekly  4
retain                  monthly 12

and this schedule:

44     2     *     *    * root   rsnapshot daily    # mon-sat 
27     0     *     *    0   root   rsnapshot weekly   # sun
17     1     1     *    *   root   rsnapshot monthly  # first of every month

this means if i start the first week from scratch, then i would have on 

saturday: daily.0 - daily.5

and on sunday i see a problem, cron would call first "rsnapshot weekly" due to the time, this will cause:

daily.6 not present (yet), nothing to copy

the result is one missing "weekly".

Can you confirm this problem ?

Regards

**Comment by m-osmani** [comment]
I would greatly appreciate it if I could have an answer to my question.

Regards

**Comment by sam-at-github** [comment]
>  If you want to ask a question or have a general discussion use the [Mailing List](https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss)

Conceptually each `retain` defines a FIFO of strictly fixed length. Each item in the queue is labelled <retain-name>.index. All `rsnapshot <retain-name>` does is rotate the queues. Given 

    retain level0 X
    retain level1 Y

In general you have to ensure level0 is called >= X times, between Y calls., otherwise you'll get "not present (yet), nothing to copy.", which isn't a huge deal normally.
