### ISSUE TITLE
rsnapshots of rsnapshots ?

### ISSUE THREAD

**Issue by stefangweichinger** [rsnapshot/rsnapshot#219]
One of my current setup runs rsnapshots of ServerA to ServerB by pulling via ssh. OK so far.
Now I would like to pull one daily rsnapshot from that set to ServerC (located remote, via OpenVPN).

Is it OK to let ServerC pull from daily.0 in rsnapshot_root on ServerB, or do I need to specify some extra parameters maybe to correctly get perms and links ... ?

**Comment by stefangweichinger** [comment]
*bump*

**Comment by DrHyde** [comment]
Should work just fine, provided that:

* you run as root on ServerC (so it can write files for any user/group);
* you ssh to root@ServerB (so it can read everything)

As you're only pulling daily.0 you don't need to worry about the hard links between daily.0, daily.1 etc, but if you want to preserve any hard links that might exist within a daily backup don't forget to use `rsync -H`.

**Comment by stefangweichinger** [comment]
thanks! So you suggest to specify (and slim down) rsync_long_args for that one specific line, right?
Right now I am at the initial big chunk of copying data at first ... and I have to tune my cronjobs so that job A-B does not start again while I do B-C.

**Comment by DrHyde** [comment]
Leave rsync_long_args alone and set it in rsync_short_args. The default value is just `-a`, I have it set to `-aSH` so that it will preserve hard links between files within one of my backup targets, and also use sparse files whenever possible to save disk space.

Note however that turning on -H makes rsync use quite a bit more memory than normal as it has to remember the inode and name of every single file it comes across so that if it comes across another name later with the same inode it knows to link the two together in the target.

**Comment by stefangweichinger** [comment]
Trying to come up with a working setup. It's a slow VPN link between the 2 machines, so I have to take care of not dropping too much data on the target while getting the paths etc right.

In fact it would be enough to somehow "mirror" the rsnapshot-tree from server B to server C.
I did an initial rsync when C and B were in the same LAN a few weeks ago, now I am rsyncing the changes over and fiddling with the "cascaded snapshots" that result from these rsnaps of rsnaps.

thanks so far

**Comment by sam-at-github** [comment]
@stefangweichinger If you want to follow this up please do so on the mailing list which is the proper mechanism for questions / discussion - https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss.
