### ISSUE TITLE
How to set up a backup to a remote host

### ISSUE THREAD

**Issue by soratobukuroneko** [rsnapshot/rsnapshot#254]
Hi,

I don't understand how I should set up my configuration to make my backup to a remote host (via ssh?)
I currently have
```
snapshot_root   /mnt/backup/rsnapshot
backup  /home/          localhost/
backup  /etc/           localhost/
backup  /usr/local/     localhost/
```

should I just change localhost by the name/IP of the server?

**Comment by StefanMoch** [comment]
> I don't understand how I should set up my configuration to make my backup to a remote host (via ssh?)

You cannot really do it this way (_push_ to another server) with rsnapshot, as it _pulls_ the backups to the machine it is running on. The backup machine needs the snapshot_root mounted locally. This directory can, however, be mounted from another server via NFS or similar, so that the data is physically on the other machine. Which may solve your problem.

> I currently have
> 
> ```
> snapshot_root   /mnt/backup/rsnapshot
> backup  /home/          localhost/
> backup  /etc/           localhost/
> backup  /usr/local/     localhost/
> ```

That backups the three directories to your backup directory in `/mnt/backup/rsnapshot`. If this directory is an NFS share, it should work.

> should I just change localhost by the name/IP of the server?

That alone will just make your data backed up a directory with another name.

The usual setup (besides the local-only case) is: If you have one backup machine and want to backup other machines, rsnapshot is configured to login to the other machine via rsync over ssh and syncs to the folder in snapshot_root. (In your example `/mnt/backup/rsnapshot/localhost/`)

The second argument of the backup line (i.e. "localhost/" in your example) is the _target directory_ in your `snapshot_root`. That should be changed if you backup another host, but it is not enough. You can name it like you want (the hostname is usually used), just make sure the backups of different hosts are synced to different target directories. The first argument also needs to be changed like `root@hostname:/home` and so on.

For configuration examples, see:
https://github.com/rsnapshot/rsnapshot/blob/master/rsnapshot.conf.default.in#L237

**Comment by DrHyde** [comment]
It's worth noting that each `backup` directive should have a different target directory. This:
```
backup  /home/          localhost/
backup  /etc/           localhost/
backup  /usr/local/     localhost/
```

will first make the contents of `$snapshot_root/localhost` a copy of the contents of `/home`, and with immediately thereafter make the contents of `$snapshot_root/localhost` a copy of the contents of `/etc`. You will no longer have a backup of `/home`. And so on.
