### ISSUE TITLE
IDEA: speed up retention rotation

### ISSUE THREAD

**Issue by mrAceT** [rsnapshot/rsnapshot#259]
Before the backup starts I see something like this:

/bin/rm -rf /backup/servers.3/
mv /backup/servers.2/ /backup/servers.3/
mv /backup/servers.1/ /backup/servers.2/
/bin/cp -al /backup/servers.0 /backup/servers.1

Since I backup quite a bit of data the 'rm' (removing) and 'cp' (copying) takes quite a bit of time. That got me wondering, wouldn't things speed up quite a bit when:

**mv /backup/servers.3/ /backup/servers.4/**
mv /backup/servers.2/ /backup/servers.3/
mv /backup/servers.1/ /backup/servers.2/
**mv /backup/servers.0/ /backup/servers.1/**
**mv /backup/servers.4/ /backup/servers.0/**
**rsync -rtu --delete /backup/servers.1/ /backup/servers.0/**

Since moving files is much faster then copying them, wouldn't using the backup that is deleted originally as a basis for the next backup speed things up greatly?

Can this be made an optional setting? Or can I even configure this now somehow with "retain"?

PS: when "backup 3" (the one that is deleted now) isn't there yet when starting backups the current structure is the way to go then naturally

**Comment by sgpinkus** [comment]
We have such an option `use_lazy_delete`. It defaults to off. Please refer to man page for details.

**Comment by mrAceT** [comment]
In the config it says:

# If enabled, rsnapshot will move the oldest directory for each interval
# to [interval_name].delete, then it will remove the lockfile and delete
# that directory just before it exits. The default is 0 (off).
#
use_lazy_deletes        1

I set it to 'one', but reading the section above, I have the impression that it is different to what I am sugesting?

**Comment by StefanMoch** [comment]
> In the config it says:
> 
> ```
> # If enabled, rsnapshot will move the oldest directory for each interval 
> # to [interval_name].delete, then it will remove the lockfile and delete
> # that directory just before it exits. The default is 0 (off).
> #
> use_lazy_deletes        1
> ```
> 
> I set it to 'one', but reading the section above, I have the impression that it is different to what I am sugesting?

It is indeed different from what you suggested, but it will help you with the delay introduced by the removal of the directory. `use_lazy_deletes` is used to delete the “rotated out” last directory at the _end_ of of the backup file rotation. If it is not set, the deletion happens first, and therefore the subsequent actions are delayed.

Coming back to your original message for some further points:

> Before the backup starts I see something like this:
> 
> /bin/rm -rf /backup/servers.3/
> mv /backup/servers.2/ /backup/servers.3/
> mv /backup/servers.1/ /backup/servers.2/
> /bin/cp -al /backup/servers.0 /backup/servers.1
> 
> Since I backup quite a bit of data the 'rm' (removing) and 'cp' (copying) takes quite a bit of time. That got me wondering, wouldn't things speed up quite a bit when:

The `cp -al` does take its time, but less than `cp -a` (full copy) would: it only copies the directory structure and puts in hardlinks (`-l`) to the existing files, so _no file content_ is copied.

> **mv /backup/servers.3/ /backup/servers.4/**
> mv /backup/servers.2/ /backup/servers.3/
> mv /backup/servers.1/ /backup/servers.2/
> **mv /backup/servers.0/ /backup/servers.1/**
> **mv /backup/servers.4/ /backup/servers.0/**
> **rsync -rtu --delete /backup/servers.1/ /backup/servers.0/**
> 
> Since moving files is much faster then copying them, wouldn't using the backup that is deleted originally as a basis for the next backup speed things up greatly?

No, generally the best basis for the new backup is the freshest one you have around (`.0`) because that has (usually) the least difference to the new data coming in, so rsync in the backup step has less data to transfer. However, your suggested rsync step for creating `.0` (with these options at least) _does_ create **copies** of files which are in `.1` but were not in `.4`/`.0`.

1. This breaks the space savings rsnapshot has by using only hardlinks for files which did not change between runs.
2. This also may or may not be faster. It could be faster because `rm` and `cp -al` are gone, it could be slower, because of actual file data being written. This depends heavily on the actual data and its turnover between backups. It is probably most advantageous with a huge backup tree, very little turnover per backup and very few rsnapshot intervals.
3. The `-u/--update` option is probably also not what you want here, because the newest directory might as well have a file with an older timestamp, so you are not necessarily re-creating the last backup state, but something in between which might have a _some_ of the last backed up files in it and others not.

There is a way to make rsync generate the hardlinks (with `--link-dest`), which could be used, if you want to pursue your idea further. But to really take advantage of this, you would have to use rsync to create the hardlinks to the unchanged files _and_ backing up the new files in one step. This is already possibly with rsnapshot:

See the [link_dest](https://github.com/rsnapshot/rsnapshot/blob/1.4.3/rsnapshot.conf.default.in#L173) option. _How does it work?_ Instead of `cp -al`ing the directory `.0` to  `.1` and then rsyncing the backup into `.0` directly (like your current rsnapshot config does with `link_dest	0`) it moves/renames `.0` to  `.1` (like you suggested) _and_ let rsync generate the whole `.0` directory and both create the hardlinks to unchanged files from `.1` and creating the new ones (from the server) in one step.

Suggestion:

```
link_dest       1
use_lazy_deletes        1
``` 

The first one _minimizes the work done_ and the second one _moves the deletion to the end._

While we are at it, I also recommend `sync_first	1` and calling `rsnapshot sync` and (only if successful) the first rotation next. See

- https://github.com/rsnapshot/rsnapshot/blob/1.4.3/rsnapshot.conf.default.in#L179
- https://github.com/rsnapshot/rsnapshot/blob/1.4.3/rsnapshot-program.pl#L7394

for configuration and calling it from cron.

This works also with the options above and tells rsync to do its work in a separate .sync directory. The first rotation moves this to `.0`. Its advantage is, that an aborted sync does not get rotated into the numbered backup directories. It does not make it faster, but more robust.


> Can this be made an optional setting? Or can I even configure this now somehow with "retain"?

That is currently not possible and would have to be implemented. I suggest not doing so, as the two suggested options above already make the backup creation more efficient.

> PS: when "backup 3" (the one that is deleted now) isn't there yet when starting backups the current structure is the way to go then naturally

Yes, when `.3` is not there yet, it does not need to get “rotated out” / deleted. One could certainly do it the way you suggested, and under certain specific circumstances (see 2. above) it might be the most efficient way to do it. However for the general case probably not.
