### ISSUE TITLE
cron - timing - interval AGAIN

### ISSUE THREAD

**Issue by jsaak** [rsnapshot/rsnapshot#264]
I see a lot of people on the internet struggling to set cron entries for daily, weekly, monthly backups.
I was thinking maybe this script would solve this typical problem?
Do you think this will work?

Run this script every day:
```
rsnapshot daily
if monday
  rsnapshot weekly
end
if first day of month
 rsnapshot monthly
end

```

**Comment by sgpinkus** [comment]
Hi @jsaak, thanks for the feedback. I think in general `rsnapshot` does not want to concern itself too much with how it's invoked because this varies too much depending on the context. It's true though that `cron` is probably not always the best solution these days. `systemd` or `anacron` are two alternatives. This wiki page show some systemd examples -- https://wiki.archlinux.org/index.php/Rsnapshot. We should probably get around to adding some more up to date details about this kind stuff in the README.

**Comment by jsaak** [comment]
The solution in arch wiki is sub-optimal, since you have to guess how long your daily backup will take.
This can be very error prone. I was thinking, the script above solves this issue.
(it can be invoked with cron or systemd or whatever)
I am just asking, if you think it is a good solution to this problem? Also would be nice to include it in a readme of some sort, if you agree, that this is the correct solution.
