### ISSUE TITLE
fresh install from fedora repo not running

### ISSUE THREAD

**Issue by RedTedRedemption** [rsnapshot/rsnapshot#269]
running any commands results in

Can't locate File/Basename.pm in @INC (you may need to install the File::Basename module) (@INC contains: /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/share/perl5/vendor_perl/File/Path.pm line 7.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/File/Path.pm line 7.
Compilation failed in require at /usr/bin/rsnapshot line 41.
BEGIN failed--compilation aborted at /usr/bin/rsnapshot line 41.

**Comment by RedTedRedemption** [comment]
For some reason PHP wasn't installed. Problem is solved. Closing Issue

**Comment by DrHyde** [comment]
Installing PHP shouldn't have fixed this! The error indicates that File::Basename is missing from your perl install. However, it has been distributed with perl ever since the very first release of perl 5 back in the 1990s! If you have the time to figure out what *actually* went wrong here I'd love to know. It might end up being a bug in Fedora's perl package that means parts of it are missing, and that should be reported to the package maintainer if it's the case.
