### ISSUE TITLE
Unclear docs/example .conf around @CMD_*@ vs cmd_*

### ISSUE THREAD

**Issue by codingthat** [rsnapshot/rsnapshot#275]
Hi team!

Hoping you can give some quick help.  I find this section a bit confusing: https://github.com/rsnapshot/rsnapshot/blob/7e5919b8ff02ed89067936dbcfd4a9d3aab8c40f/rsnapshot.conf.default.in#L40 vs. lines 35-36, for example.

Contrast that with https://github.com/rsnapshot/rsnapshot/blob/master/docs/HOWTOs/rsnapshot-HOWTO.en.html or https://linux.die.net/man/1/rsnapshot which refer to `cmd_cp`.

What does just uncommenting the line (as it is) do / how magical is it?  Does it just fill in a default value, or go searching?  For example, the default value listed in https://linux.die.net/man/1/rsnapshot for `cmd_du` is not correct on my system.  If I uncomment `@CMD_DU@`, will it do the right thing?

If not, I assume `@CMD_DU@\t/correct/path/to/du` isn't right and that I need something like `cmd_du\t/correct/path/to/du` instead.  `# EXTERNAL PROGRAM DEPENDENCIES #` could use an overall note about this—I'd be happy to add one myself once this is clarified.  ✔  Thanks!

**Comment by codingthat** [comment]
(Related, I'd love to know why the `@` pattern ends with `cmd_rsnapshot_diff`.  Does it do anything for normal usage, or only if you want to run `rsnapshot diff`?)

**Comment by codingthat** [comment]
My bad: I now see that's supposed to get replaced on install, hence the `.in`.  In my particular case, /etc/rsnapshot.conf.default did not exist after package installation, but that's also not where rsnapshot was looking for it when I ran it.

So that part's OK.  Still curious about rsnapshot_diff though :)

**Comment by StefanMoch** [comment]
All replaced patterns like `@CMD_DU@` are for _external commands,_ that rsnapshot either requires or optionally can use. These may or may not be installed on the system and can have different paths depending on the system.

The substitutions are defined in [configure.ac](https://github.com/rsnapshot/rsnapshot/blob/7e5919b8ff02ed89067936dbcfd4a9d3aab8c40f/configure.ac), so with running `./configure`:

- the correct path for each command is located and, if found, written to rsnapshot.conf.default, or
- the path to each command can optionally be specified via command line switches to `./configure`
- if not found and optional: a generic `/path/to/` is prepended, or
- if not found and required: the file is not written and configure stops with an error message

`rsnapshot-diff`, on the other hand, comes _with_ the rsnapshot source, it is not an required or optional dependency.

(The hard-coded path (`/usr/local/bin/rsnapshot-diff`) in `rsnapshot.conf.default.in` is however only correct if the installation path is not changed (with `--prefix`) from the default `/usr/local`. But since this line is commented and rsnapshot is falling back on `$PATH` if `cmd_rsnapshot_diff` is not defined, it should be fine.)

**Comment by codingthat** [comment]
Thanks, @StefanMoch, that makes sense.  And from the looks of https://github.com/rsnapshot/rsnapshot/blob/35ee81e1ff9b7774661367165b7f07df32f91175/rsnapshot-program.pl if `cmd_rsnapshot_diff` happens to be wrong (because of a `--prefix`'d installation) that would only cause problems with direct invocations of `rsnapshot diff`.
