### ISSUE TITLE
rsnapshot removal in debian bullseye

### ISSUE THREAD

**Issue by Yannik** [rsnapshot/rsnapshot#279]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986709

The rsnapshot package is being removed in the next debian release.

That really hurts, as I use rsnapshot heavily.

**Comment by sgpinkus** [comment]
Yeah definitely handy if rsnapshot is in Debian archive for me too!

Weird. I think the old packager left, Michael Lustfield picked it up recently? Then came to his own conclusion that this package is not maintained w/o really telling anyone here. Instead of declaring:

> This project is essentially dead and no longer suitable for inclusion in the Debian archive... or for use on any system.

Would be better if Michael actually pointed to open issues that are not being attended to. What are they? It's true there is *definitely* a feature freeze in place since @bebehei left (it's "stable" software ..). And it's true master is ahead last formal version bump (I will get onto that!), but I still think rsnapshot should be in Debian.

**Comment by MTecknology** [comment]
> Would be better if Michael actually pointed to open issues that are not being attended to. What are they? It's true there is *definitely* a feature freeze in place since @bebehei left (it's "stable" software ..). And it's true master is ahead last formal version bump (I will get onto that!), but I still think rsnapshot should be in Debian.

I had two pull requests that were open for a year that I even pinged you about
via email. I made other attempts to discuss rsnapshot with you, but received
between limited and no response.

I did not take that decision lightly, particularly since rsnapshot is software
that I have relied on for a very long time and understand it's value even in a
no-new-features state. Picking apart each reason feels like a recipe for
building strawman arguments and I'd like to avoid that.

What's most important... if you truly believe I'm wrong and that rsnapshot has
appropriate maintenance, I'm not in any way blocking it from re-entry. Any DD
is able to re-upload it very easily. I actually copied someone in this message
that may have some interest here.

Note: Prior to an upload, they /should/ try to fix the open debian bugs:
- https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=rsnapshot
  + #934349 seems to have only a subject/title... :/

Cheers,
-- 
Michael Lustfield

**Comment by sgpinkus** [comment]
Not interested in straw man arguments either.

@MTecknology Seems like no release date has been set for bullseye yet so we have time to get it back in so long as some DD is will to take it up? Regarding issues, I think I concluded issues you raise were "won't fix" or PR had issues (like no tests) or didn't exist, but can't recall exactly. 

I will find sometime next week to review open Debian issues and try to  cross ref them with open issues here, do some spring cleaning of open issues and PRs, and do a release. More than likely most issue won't be fixed though, but we'll see.

**Comment by bebehei** [comment]
I started mainting this, while being a student. On both companies, I've worked now, I've often found an installation of rsnapshot. I'm honest - it was cruel. But actually it's dependent software and I don't understand it, that Debian wants to remove it.

Debian#934349 Is basically a [patch for the first line in `configure.ac`](https://github.com/rsnapshot/rsnapshot/blob/54163c43026c508d9029d476739cd7904ac396fa/configure.ac#L1).

**Comment by Yannik** [comment]
@shodanshok I think you would need to address this here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986709

**Comment by sgpinkus** [comment]
Update: I've given a once over of all issues on debian bug trackers, this Github's issues and PRs.

  - There are 7 open PRs here. All of them have been marked as needing tests, or incomplete. They are all either features or low severity bugs.
  - There's 27 open issues, for a mix of things feature requests and minor issues. But no critical bugs, or things that don't have work arounds. I've pinned the ones that I think should be fixed, and have a chance of being fixed in a later release (just two for now #284, #281).
  - Of the Debian bug tracker issues, a couple relate to #284, which could be left open or closed, others relate to packaging issues.  One is "whitespace instead of tabs ..." which is a won't fix for foreseeable. The rest can be closed as they have been fixed already, or fixed in the latest version ->
  - I've just gone ahead and done a patch version bump to 1.4.4. See [Changelog](https://github.com/rsnapshot/rsnapshot/blob/master/ChangeLog). Packagers should use this in new packages.

**Comment by tapanitarvainen** [comment]
Note that while it's too late now to get it back to Bullseye main repository, getting it into bullseye-backports should be possible and probably not all that hard either.

**Comment by kevinlyles** [comment]
I think you meant to tag @kanlukasz.

**Comment by sgpinkus** [comment]
@nodiscc will look into it.

**Comment by gqdc** [comment]
> 
> 
> I've added a .deb to website and to Github releases for v1.4.4. It's based off the Debian buster 1.4.2 package source. Had to simplify it a little bit and removed some outdated package patches. Hopefully it's still fine. Also pushed branch with build source to `debian-build` so if any issues, can PR against that branch :).

Hi, the next link to the .deb is actually dead : https://rsnapshot.org/downloads/rsnapshot-1.4.4-1_all.deb

**Comment by classic0** [comment]
Baffled by "Unable to locate package rsnapshot". But huh, that wget is not gonna look great! Anyway thanks, I am already too dependent on it.

**Comment by Devenet** [comment]
Thanks a lot for the build of the `.deb` package!
Also, very sad that it’s not in Bullseye, but it is like this.

**Comment by teadur** [comment]
So i understand correctly that no-one is willing to pick up the maintenance ?

**Comment by chuegel** [comment]
This is truly sad as I use rsnapshot on a daily basis

**Comment by cebe** [comment]
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986709#117

> With Michael's agreement, I have taken over maintaining rsnapshot. I have just
uploaded version 1.4.4-1.

seems it will be back soon.

**Comment by dmagre** [comment]
Great work. Thanks!

**Comment by DrHyde** [comment]
So does this mean we can close the ticket?

**Comment by Yannik** [comment]
I think so! :-)
