### ISSUE TITLE
Difference between snapshot_root and backup points

### ISSUE THREAD

**Issue by KayTaneJupiter** [rsnapshot/rsnapshot#292]
I don't understand the difference between snapshot_root and backup points in the rsnapshot.conf file.

If I  setsnapshot_root to MyBackupsGoHere why would I want rsnapshot to further bury the backups with another directory like "localhost/" ?

For example, if I want to run daily backups of  /home/

... I expect to find them in MyBackupsGoHere/daily.0/home/ 

... not MyBackupsGoHere/daily.0/localhost/home/

The "localhost" subdir seems unnecessary. Why is it there? Can I get rid of it?

**Comment by DrHyde** [comment]
Github Issues are for reporting bugs and asking for new features. Please direct support requests to the mailing list in future. You will generally get a quicker response there.

The intermdeiate directory is there because rsnapshot is designed to back up multiple sources, and if you try to backup /home from localhost and /home from remotehost both to MyBackupsGoHere/daily.0/home you're going to lose data.

If you've only got one source (one backup point) which is the /home directory on the same machine that will host your backups, and you know that you will never add a second backup point, then you should be able to do this:
    backup    /home    .

But it's not recommended.
