### ISSUE TITLE
immutable backup with rsnapshot

### ISSUE THREAD

**Issue by pvanthony** [rsnapshot/rsnapshot#353]
### Checklist

- [X] I'm asking for a feature to be changed or added
- [X] I've searched the [bugtracker](https://github.com/rsnapshot/rsnapshot/issues) for similar issues, including closed ones.
- [X] I realise that rsnapshot is stable software and most feature requests will be rejected

### My suggestion is ...

I was wondering if it is possible to have a immutable backup with rsnapshot on xfs filesystem.
If not directly in rsnapshot, is it possible with a bash script?
Any links would be great.
Tried searching but could not find.

### Why I want it

With ransomware, this might be a good solution.

### Why should this be in rsnapshot and not implemented using some external tool?

It can be an external tool. If there is one, please do share.

**Comment by DrHyde** [comment]
rsnapshot needs to run as a priveleged user anyway, because otherwise it can't properly back up permissions/ownership, so rsnapshot _could_ do this. There are a few things to think about.

For a typical home user, rsnapshot runs on a machine that the user also uses as a non-priveleged user for day-to-day stuff, and that user can normally `sudo` to root. That means that if ransomware gets onto that machine it can trick the user into running the ransomware as root, at which point the ransomware could just make the files mutable again. If you have a savvy user who is unlikely to just blindly type their password when asked for it, then setting your `snapshot_root` to be `chmod 700; chown root` is sufficient protection against ransomware running as an ordinary user.

In larger installations rsnapshot runs on a dedicated machine which is much better protected (mostly by just not being used for anything risky) at which point ransomware is far less of a worry.

But ignoring that, we also need to bear in mind that rsnapshot (running as root, remember) needs to be able to alter previous backups. It needs to be able to rename them, and to delete old ones when it rotates backups. So rsnapshot needs to be aware of immutability and be able to turn it on and off. We do have some filesystem-specific (well, volume-manager-specific) code, to do with handling Linux LVM, but in retrospect that was a bad idea, and I think we're unlikely to put something XFS-specific in. So any patch would have to be generic enough to handle _any_ filesystem's immutability capabilities. How this is done differs from one OS to another and also one FS to another.

This all sounds like a fair amount of work and hard to test, for not much benefit.

I think you would be better off using your own script, which we would be happy to add to the repository so that others can benefit from it.

Finally, you might like to listen to [the most recent episode of the "2.5 admins" podcast](https://2.5admins.com/2-5-admins-220/), in which they talk about backups and ransomware. They're very "rah rah zfs" (for good reason IMO) but most of what they say applies more generally.

**Comment by pvanthony** [comment]
Thank you very much for the detailed explanation. I do appreciate it very much.

I do use rsnapshot to backup linux servers. The backup server is another machine.

rsnapshot is amazing!!!

Thank you for sharing.
