### ISSUE TITLE
exclude not working as expected

### ISSUE THREAD

**Issue by mnagel** [rsnapshot/rsnapshot#45]
my config looks like this

```
include_conf	config/GLOBAL.rsnap

snapshot_root	/home/BACKUPS/rsnap/demo/

exclude	"/e/"

# nailworks
#backup	nailor@localhost:/home/nailor/code/datenplan/rsnapshot/demo/	demo/
backup	/home/nailor/code/datenplan/rsnapshot/demo/	demo/
```

the demo folder looks like this
```
nailor@sting:*datenplan/rsnapshot$ tree demo                
demo
├── a
├── b
├── c
│   ├── c1
│   └── c2
├── d
│   └── d1
└── e
    ├── e1
    └── ee
        └── ee1

4 directories, 7 files
```

I call rsnapshot sync (not the first run, so not all files are transferred) and this is the output
```
echo 31274 > /home/nailor/code/datenplan/rsnapshot/rsnap.lock 
/usr/bin/rsync -avPx --numeric-ids --partial --delete --delete-excluded \
    --stats --exclude="/e/" /home/nailor/code/datenplan/rsnapshot/demo/ \
    /home/BACKUPS/rsnap/demo/.sync/demo/ 
sending incremental file list
e/
e/e1
              0 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=2/12)
e/ee/
e/ee/ee1
              0 100%    0.00kB/s    0:00:00 (xfr#2, to-chk=0/12)

Number of files: 12 (reg: 7, dir: 5)
Number of created files: 4 (reg: 2, dir: 2)
Number of deleted files: 0
Number of regular files transferred: 2
Total file size: 0 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 364
Total bytes received: 71

sent 364 bytes  received 71 bytes  870.00 bytes/sec
total size is 0  speedup is 0.00
touch /home/BACKUPS/rsnap/demo/.sync/ 
rm -f /home/nailor/code/datenplan/rsnapshot/rsnap.lock
```

WHY IS `e` TRANSFERRED!?!

If I run the exact rsync command listed in the log, `e` is not transferred / it is deleted when rsnapshot created it before:

```
nailor@sting:*datenplan/rsnapshot$ /usr/bin/rsync -avPx --numeric-ids --partial --delete --delete-excluded \
>     --stats --exclude="/e/" /home/nailor/code/datenplan/rsnapshot/demo/ \
>     /home/BACKUPS/rsnap/demo/.sync/demo/
sending incremental file list
deleting e/ee/ee1
deleting e/ee/
deleting e/e1
deleting e/

Number of files: 8 (reg: 5, dir: 3)
Number of created files: 0
Number of deleted files: 4 (reg: 2, dir: 2)
Number of regular files transferred: 0
Total file size: 0 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 187
Total bytes received: 56

sent 187 bytes  received 56 bytes  486.00 bytes/sec
total size is 0  speedup is 0.00
```

I am running Ubuntu 14.04 and the packaged rsnaphot is rsnapshot 1.3.1.

Any ideas?

Thanks,
Michael

**Comment by lathspell** [comment]
This sounds pretty much like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743310 
From what I remember from personal experience, it did work in 1.3.0, was broken in 1.3.1 and worked again using a 1.3.2 GIT checkout from about September 2013. This project sadly seems kind of dead.

**Comment by myrdd** [comment]
> This project sadly seems kind of dead

Yes, sadly. If someone would fork this project, I'm willing to help!

**Comment by bebehei** [comment]
Hey guys, I don't want to fork the project but I'm willing to contribute to. I already did a PR, but in general noone answered to any PR for the last few months.

Luckily I found by accident a message on rsnapshot-maintainers a few days ago:
http://sourceforge.net/p/rsnapshot/mailman/rsnapshot-maintainers/thread/20141014160734.GA8275%40bytemark.barnyard.co.uk/#msg32930724

As I see it there, the maintainers are willing to give the project into other hands, but sadly nothing happened since october.

So I asked David Cantrell, the author of this message. (Please read the linked thread first!)
>> //Benedikt Heine:
>> You stated in October on the rsnapshot-maintainers-list, that you won't
>> maintain rsnapshot anymore. Did you find someone, who is the new "Captain
>> of the rsnapshot-ship"?
>
> //David Cantrell:
> I didn't, but David Keegel indicated that he might have a bit more time.

(my bad, I haven't replied yet to this)

"forking" is in my opinion not the right way to go. As you will loose a big userbasis, what you have to gain again. Additionally you have to look forward to get into the repos of the distributions, too. Handing the maintenance over to a team will be IMO one of the best options. I personally don't want to be the lead, cause I never did this before. But as everyone has got his first time, I possibly could do this if someone guides me.

In general, I would like to see a few persons teaming up, taking together the lead and developing rsnapshot further. I want to be one member of that team. (Maybe @myrdd too?)

In my own repo I started to work on it a few days ago. There are plenty of little bugs and few features requested which are nice to have. Many of them are already fixed in a Pull Requrest, but they didn't get merged. As David said in his first mail, this is the main work to do by now.

If there will be a team, working together on rsnapshot, I will see the project going forward very well. And if we look forward and get a big stable version-bump before freezes of major distros, we could achieve really effective work.

Additionally, I will link here @sam-at-github and @kevinlyles . They may be interested, as they have made big PRs.

As I think neither this message, nor any answer to it is located right in this thread, we should use for further discussion, either rsnapshot-maintainers or rsnapshot-discuss.

**Comment by myrdd** [comment]
Thanks for your investigation @bebehei ! I agree with you that forking wouldn't be the way to go. I rather meant trying to merge the PRs together on a new branch and testing those PRs as a first step.

> I personally don't want to be the lead

Me neither, I'm working a lot on [RequestPolicy](https://github.com/RequestPolicyContinued/requestpolicy). But I'd gladly help what I can. However, I've never really programmed Perl before, so what I would do is reviewing commits, read issues and maybe write some unit tests.

> get a big stable version-bump before freezes of major distros

Will distros drop unmaintained software? reasonable…

> we should use for further discussion, either rsnapshot-maintainers or rsnapshot-discuss.

I've added myself to the lists. `rsnapshot-maintainers` is a moderated list though, I'm not yet on it.

**Comment by sam-at-github** [comment]
@bebehei Good find on the call out for new maintainers email. I didn't catch this on the general mailing list. Wonder if it was ever posted there?

Agree with @myrdd, someone should bring this up on users mailing list. I would also create a new issue here to discuss this further.

But briefly, the situation with this repo, is that there is one tagged commit "1.3.1", which I'll assume is what most apt based repos are packaging off (its what is on stable debian repos at least). There is a significant number of commits (around 50) after that tag (from 2008) with no version bumps (no tags). This makes things hard (at least appears to). All the changes in those commits are untested, and someone - the maintainer going forward - is going to have to understand what they are, how to deal with them all. Are they backward compatible? Are they new features? Having said that they don't look all that major. Then again the rsnapshot source code is a bit hairy.

I have no real interest in maintaining rsnapshot. I personally don't have any big ideas for future development either. I like it that way it is, except for the bugs and odd and end that could be improved. But I will definitely help out and stay tuned.

My opinion on what needs to happen:

  + Make github the primary focus. Mirror to source forge if you want. I would forget the rest.
  + Start using [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) development model very next thing. I would actually rebase master to "1.3.1." and take HEAD, as the new dev branch.
  + tidy the source code, write a coding std, write a CONTRIBUTING.md that refers to the coding std, outlines how to run the tests, and encourages writing tests (I already tried to PR such along time ago).
  + Figure out WTF those 50 odd commits did, decide if they can all go in a single minor version, or how to cut them up. Then start tagging releases and merging them into master.

Finally, yeah thanks for the effort @bebehei.

**Comment by mnagel** [comment]
+1 for moving this discussion to a new github issue
+1 for moving to github
+1 for improved unit tests
+0.5 for gitflow

**Comment by bebehei** [comment]
@mnagel have you found a solution. Sadly, the use of rsyncs exclude is quite complicated, in comparison to the rest of the rsnapshot-file. If you still experience trouble, consider using rsnapshot-discuss[0]. There are much more helping minds available than on github.

If you have an exact knowledge, how to change the behaviour of this feature, i would like to see you open a bug-report.

[0]http://sourceforge.net/p/rsnapshot/mailman/rsnapshot-discuss/
