### ISSUE TITLE
"ssh_args" does not work due to lack of quoting

### ISSUE THREAD

**Issue by tedivm** [rsnapshot/rsnapshot#89]
If you set ssh_args to anything it gets added to the rsync command directly-

> --rsh=/usr/bin/ssh -p 222

As a result those extra arguments look like arguments for rsync itself. Enclosing them in quotes would make them actually work-

> --rsh="/usr/bin/ssh -p 222"

The relevant code is on line [3735](https://github.com/rsnapshot/rsnapshot/blob/master/rsnapshot-program.pl#L3735).

**Comment by bebehei** [comment]
You use the current master and **not** 1.3.1?

Have you had a look at #15? This PR changed the code into opposite.

**Comment by tedivm** [comment]
I use 1.3.1. 

I don't get why they think that solved the problem, because it certainly did not- as I said it breaks for me when using a differnet port.

The way I solved this was by leaving -rsh=/usr/bin/ssh alone, but adding the e option to the rsync_long_arguments config value in with the custom ssh options-

> -e "ssh -p 222"

This resulting in a working system for me.

**Comment by bebehei** [comment]
> I use 1.3.1.
>
> I don't get why they think that solved the problem, because it certainly did not- as I said it breaks for me when using a differnet port.

I tested it now on my machine. I neither hit an issue with the ArchLinux 1.3.1 Version, nor the current master. Config from #15
```
config_version	1.2
snapshot_root	/tmp/snapshots/
cmd_rsync		/usr/bin/rsync
cmd_ssh	/usr/bin/ssh
ssh_args	-p 200
interval		hourly	6
backup			user@nowhere.com:/tmp/file	localhost/
```

If you could to post config, which breaks the setup, this would bring us forward.

@sam-at-github has probably more knowledge in this issue. Maybe he can help better.

> The way I solved this was by leaving -rsh=/usr/bin/ssh alone, but adding the e option to the rsync_long_arguments config value in with the custom ssh options-
>
>> -e "ssh -p 222"
>
> This resulting in a working system for me.

Yes, this option got proposed by others, too.

**Comment by sam-at-github** [comment]
If you check out tag 1.3.1 you'll see the last commit to it was done in 2008. There was a bunch of commits on master since then (@bebehei if I recall you counted 90?). I think most distros/repos were taking something other than the 1.3.1 tagged version (unless that tag has been moved since??). The problem does not exist in the currently git tagged 1.3.1 but it most definitely existed in the version pulled from the debian stable at the time #15 was filed.

To be be honest at a glance, I can't see why this problem did not occur in the 2008 version. I remember something about it being fixed then reintroduced. I *can* see why it occurred in the code base #15 was pushed against as I described in #15. Please read the comments there.
